### ISSUE TITLE
Arch Linux AUR package created

### ISSUE THREAD

**Issue by simonbcn** [ozeidan/gosearch#2]
I've installed your program and I really find it very useful and really efficient and fast.
So I created a package to install it easily on Arch Linux: https://aur.archlinux.org/packages/gosearch-git/

I don't use your makefile, it gave me problems to use with the Arch installation system, instead I compile and install the files.
I hope it will help more people to use your program.

**Comment by ozeidan** [comment]
Hi @simonbcn, thanks a lot for creating the package! I tried it and it works nicely.

This was on my todo list already but I couldn't piece together the packaging system. So your contribution is highly appreciated :slightly_smiling_face: 

I noticed that you are copying the service file to `/usr/lib/systemd/system/` in your script. Would you suggest also doing so in the Makefile?
The Makefile should probably also install the client to `/usr/bin`, so that no working GOPATH is needed.

**Comment by simonbcn** [comment]
In my first test I installed the service file in the same directory as your `Makefile`. But when I checked the package created with `namcap` (_a Pacman package analyzer_) it suggested that I should install it better in `/usr/lib/systemd/system`.  
I have consulted the [Systemd wiki](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path) and it indicates the following:
>...
> /etc/systemd/system : System units created by the administrator
>...
> /usr/lib/systemd/system : System units installed by the distribution package manager
>...

So I think in the case of your `Makefile` you should keep using `/etc/systemd/system` and in my case, as it is installed by Arch package manager, it is best to use `/usr/lib/systemd/system`.

I think the executable files is better in `/usr/bin` or `/usr/local/bin`. Unless they're executable that we don't want to be executed by the user.

**Comment by vredesbyyrd** [comment]
Appreciate you packaging this for arch. I attempted to create a PKGBUILD myself a few days ago but was unsuccessful. Cheers.
